import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { AuthCheck } from "@/components/common/AuthCheck";
import { Toaster } from "react-hot-toast";
import Header from "@/components/common/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-right" />
        <AuthCheck>{children}</AuthCheck>
      </body>
    </html>
  );
}
